### ISSUE TITLE
After logging in, go to people and still see log in button

### ISSUE THREAD

**Issue by mihneadb** [rosedu/events#49] opened 2015-05-10 14:18 UTC
Steps:
* go to homepage
* press log in button
* log in
* [ you are logged in ]
* go to people
* log in button still shows up (why?)

**Comment by fullvlad** [comment] 2015-05-10 15:07
This is a known bug, @Aleks23  is currently assigned to it.
The problem is that G+ "Sign in" button appears and not the "Logout", even though you're logged in for that session.

**Closed** 2015-10-01 14:42 UTC
Labels: bug
